spring.application.name=booktheshow

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/booktheshow
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=INFO

booktheshow.security.jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0SldUS2V5Rm9yQm9va1RoZVNob3dBcHBsaWNhdGlvbg==
booktheshow.security.jwt.access-token-expiration-ms=900000
booktheshow.security.jwt.refresh-token-expiration-ms=604800000

booktheshow.security.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173